version: "3.7"
services:
  api-service:
    container_name: ec-service
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - mongodb:mongo
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo
    image: "mongo:4.4.2"
    restart: always
    ports:
      - 27017:27017