airtable:
  apiKey: keyAV2tLLGtrqdCmI
  baseKey: app5XDeHi6wze090M
  tableName: Businesses Out of Russia - Full Database

springdoc:
  api-docs:
    path: /api-docs

spring.data.mongodb.host: mongo
spring.data.mongodb.port: 27017
spring.data.mongodb.database: exit-companies